"""Corrige el nombre del campo about_me en el model User

Revision ID: 9aea8cd59d3c
Revises: 7ee82ead7535
Create Date: 2018-09-28 10:29:52.294032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aea8cd59d3c'
down_revision = '7ee82ead7535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('aout_me', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
